import { ChargingSession, ChargingStation, Notification } from "@/types";

export const mockStations: ChargingStation[] = [
  {
    id: "1",
    name: "ТЦ Дордой Плаза",
    address: "ул. Московская, 42, Бишкек",
    latitude: 42.8746,
    longitude: 74.5698,
    power: 50,
    connectorType: "CCS",
    pricePerKwh: 15,
    status: "available",
    distance: 2.5,
    isFavorite: false,
  },
  {
    id: "2",
    name: "ТЦ Ала-Тоо",
    address: "ул. Чуй, 155, Бишкек",
    latitude: 42.8756,
    longitude: 74.5898,
    power: 22,
    connectorType: "Type2",
    pricePerKwh: 12,
    status: "occupied",
    distance: 1.8,
    isFavorite: true,
  },
  {
    id: "3",
    name: "Hyatt Regency",
    address: "ул. Абдрахманова, 191, Бишкек",
    latitude: 42.8656,
    longitude: 74.5798,
    power: 150,
    connectorType: "Tesla",
    pricePerKwh: 25,
    status: "available",
    distance: 3.2,
    isFavorite: false,
  },
  {
    id: "4",
    name: "ТЦ Айчурек",
    address: "ул. Жибек-Жолу, 124, Бишкек",
    latitude: 42.8846,
    longitude: 74.5598,
    power: 75,
    connectorType: "CHAdeMO",
    pricePerKwh: 18,
    status: "maintenance",
    distance: 4.1,
    isFavorite: false,
  },
  {
    id: "5",
    name: "Бишкек Парк",
    address: "ул. Ахунбаева, 67, Бишкек",
    latitude: 42.8546,
    longitude: 74.5898,
    power: 100,
    connectorType: "CCS",
    pricePerKwh: 20,
    status: "available",
    distance: 5.3,
    isFavorite: true,
  },
];

export const mockChargingHistory: ChargingSession[] = [
  {
    id: "1",
    stationId: "1",
    stationName: "ТЦ Дордой Плаза",
    stationAddress: "ул. Московская, 42, Бишкек",
    startTime: "2024-01-15T10:30:00Z",
    endTime: "2024-01-15T11:15:00Z",
    energyConsumed: 35.5,
    cost: 532.5,
    status: "completed",
  },
  {
    id: "2",
    stationId: "2",
    stationName: "ТЦ Ала-Тоо",
    stationAddress: "ул. Чуй, 155, Бишкек",
    startTime: "2024-01-12T14:20:00Z",
    endTime: "2024-01-12T16:45:00Z",
    energyConsumed: 48.2,
    cost: 578.4,
    status: "completed",
  },
  {
    id: "3",
    stationId: "3",
    stationName: "ТЦ Азия Молл",
    stationAddress: "ул. Чуй, 155, Бишкек",
    startTime: "2024-01-12T14:20:00Z",
    endTime: "2024-01-12T16:45:00Z",
    energyConsumed: 53.2,
    cost: 750.4,
    status: "active",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "1",
    title: "Новое уведомление",
    message: "Текст уведомления 1",
    timestamp: "2024-01-15T10:30:00Z",
    isRead: false,
    type: "charging_complete",
  },
  {
    id: "2",
    title: "Новое уведомление",
    message: "Текст уведомления 2",
    timestamp: "2024-01-12T14:20:00Z",
    isRead: false,
    type: "charging_complete",
  },
  {
    id: "3",
    title: "Новое уведомление",
    message: "Текст уведомления 3",
    timestamp: "2024-01-10T09:15:00Z",
    isRead: true,
    type: "charging_complete",
  },
  {
    id: "4",
    title: "Новое уведомление",
    message: "Текст уведомления 4",
    timestamp: "2024-01-08T16:45:00Z",
    isRead: true,
    type: "charging_complete",
  },
  {
    id: "5",
    title: "Новое уведомление",
    message: "Текст уведомления 5",
    timestamp: "2024-01-05T11:30:00Z",
    isRead: true,
    type: "charging_complete",
  },
];
